cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),   #URL do carrinho de compras
    path('orders/', include('orders.urls', namespace='orders')),   #URL de pedidos
    path('', include('shop.urls', namespace='shop')),   #incluir a URL shop em um namespace personalizado chamado shop

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),   #chama a lista de produto sem parâmetros
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),   #chama a lista de produtos com o parâmetro de categoria, para filtrar os produtos pela categoriaS
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),   #passa o id e o slug para acessar um produto específico
    path("login", views.login, name='login')
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICE = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):   #fomrulário para adicionar produtos no carrinho
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICE, coerce=int)   #permite adicionar de 1 a 20 itens no carrinho e converte a entrada para int
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)   #informa a quantidade a ser somada a uma quantidade existente, ou a quantidade existente deve ser sobrescrita

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST

def cart_add(request, product_id):   #adiciona ou atualiza a quantidade de produtos existentes
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')   #exibirá o conteúdo do carrinho

@require_POST
def cart_remove(request, product_id):   #remover item do carrinho
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):   #exibir o carrinho de compras e seus itens
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}

{% load static %}

{% block title %}
Seu carrinho de compras
{% endblock %}

{% block content %}
  <h1>Seu carrinho de compras</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Imagem</th>
        <th>Produto</th>
        <th>Quantidade</th>
        <th>Remover</th>
        <th>Preço unitário</th>
        <th>Preço</th>
      </tr>
    </thead>
        <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Atualizar">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "cart:cart_remove" product.id %}" method="post">
                <input type="submit" value="Remover">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">R${{ item.price }}</td>
            <td class="num">R${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">R${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button
    light">Continue comprando</a>
    <a href="{% url "orders:order_create" %}" class="button">Finalizar</a>
  </p>
{% endblock %}