cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),   #URL do carrinho de compras
    path('orders/', include('orders.urls', namespace='orders')),   #URL de pedidos
    path('', include('shop.urls', namespace='shop')),   #incluir a URL shop em um namespace personalizado chamado shop

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),   #chama a lista de produto sem parâmetros
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),   #chama a lista de produtos com o parâmetro de categoria, para filtrar os produtos pela categoriaS
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),   #passa o id e o slug para acessar um produto específico
    path("login", views.login, name='login')
]

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)   #nome da categoria
    slug = models.SlugField(max_length=200, unique=True)   #slug para criação de indice

    class Meta:
        ordering = ('name',)  
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):   #obter o URL de um objeto
        return reverse('shop:product_list_by_category', args=[self.slug])
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)   #relacionamento (one-to-many) um para muitos - um produto pertence a uma categoria e uma categoria contém vários produtos
    name = models.CharField(max_length=200, db_index=True)   #nome do produto
    slug = models.SlugField(max_length=200, db_index=True)   #serve para compor URLs elegantes
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)   #imagem opcional para os produtos
    description = models.TextField(blank=True)   #descrição opcional para o produto
    price = models.DecimalField(max_digits=10, decimal_places=2)   #campo de preço
    available = models.BooleanField(default=True)   #campo booleano para informar se o produto esta disponível, será usado para ativar/desativar o produto nos catálogos
    created = models.DateTimeField(auto_now_add=True)   #armazena a data de criação
    updated = models.DateTimeField(auto_now=True)   #armazena quando o produto foi atualizado pela última vez
    
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):   #obter o URL de um objeto
        return reverse('shop:product_detail', args=[self.id, self.slug])
    

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category': category, 'categories': categories, 'products': products})

def product_detail(request, id, slug):   #espera os parâmetros id e slug para obter a nstância de produto
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

def login(request):   #espera os parâmetros id e slug para obter a nstância de produto
    return render(request, 'shop/login.html')

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}X-Podrão Lanches{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>

   <nav class="navbar navbar-light" style="background-color: #ff;">
      <div class="container-fluid">
        <a href="/" class="navbar-brand">X-Podrão Lanches</a>
        <a href="{% url "shop:login" %}" class="btn btn-light" type="submit">Admin</a>
      </div>
    </nav>

    <div id="subheader">
      <div class="cart">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            Seu carrinho:
            <a href="{% url "cart:cart_detail" %}">
              {{ total_items }} item{{ total_items|pluralize }},
              R${{ cart.get_total_price }}
            </a>
          {% else %}
            Seu carrinho está vazio.
          {% endif %}
        {% endwith %}
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
    <footer class="footer-basic-centered">

			<a href="/" class="footer-company-motto">X-Podrão<br>Lanches</a>
            <p></p>
            <p> <font color ="#8f9296">Nossa missão é servir o pior lanche da região</font></p>

			<p class="footer-company-name">X-Podrão Lanches &copy; 2021</p>
      <hr noshade>
      <p class="footer-company-name">Desenvolvido pelos alunos: </p>
      <p class="footer-company-name">Marcelo do Nascimento</p>
      <p class="footer-company-name">Titione Falacio de Amorim</p>


		</footer>
  </body>
</html>

shop/templates/shop/login.html
{% extends "shop/base.html" %}

{% load static %}

{% block title %}
Seu carrinho de compras
{% endblock %}

{% block content %}
<link href="{% static "css/base.css" %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<!------ Include the above in your HEAD tag ---------->

<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card border-0 shadow rounded-3 my-5">
          <div class="card-body p-4 p-sm-5">
            <h5 class="card-title text-center mb-5 fw-light fs-5">LOGIN</h5>
            <form>
              <div class="form-floating mb-3">
                <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                <label for="floatingInput">E-Mail</label>
              </div>
              <div class="form-floating mb-3">
                <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword">Senha</label>
              </div>
              <div class="d-grid">
                <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">Login</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

{% endblock %}